import { execSync } from 'child_process';

export interface GitHubIssue {
  number: number;
  title: string;
  createdAt?: string;
  body: string;
  labels: Array<{ name: string }>;
  comments: Array<{
    body: string;
    author: { login: string };
    createdAt: string;
  }>;
}

export interface GitHubPR {
  number: number;
  title: string;
  headRefName: string;
  body: string;
  reviews: Array<{
    state: string;
    author: { login: string };
    submittedAt: string;
  }>;
  comments: Array<{
    body: string;
    author: { login: string };
    createdAt: string;
  }>;
}

/**
 * Execute GitHub CLI command and parse JSON response.
 */
export function gh(command: string, cwd?: string): any {
  try {
    const result = execSync(`gh ${command}`, {
      encoding: 'utf-8',
      cwd,
      stdio: ['pipe', 'pipe', 'inherit']
    });
    return command.includes('--json') ? JSON.parse(result) : result;
  } catch (error) {
    console.error(`[GH CLI Error]: ${command}`, error);
    throw error;
  }
}

/**
 * Status-only bot comments that don't ask for human input.
 * These should not reset the reply-detection window.
 */
const BOT_STATUS_PHRASES = [
  'Clarification received',
  'Routing back',
  'Spec approved',
  'PR approved',
  'Review feedback detected',
];

function isBotStatusComment(body: string): boolean {
  const trimmed = body.replace(/^🤖\s*/, '').trim();
  return BOT_STATUS_PHRASES.some(phrase => trimmed.startsWith(phrase));
}

/**
 * Robustly detect if a comment was generated by an agent.
 * Handles cases where the agent might have forgotten the 🤖 prefix.
 */
export function isBotComment(body: string): boolean {
  const text = body.trim();
  if (text.startsWith('🤖')) return true;
  if (text.includes('**[AtomoDev]:**')) return true;
  if (text.includes('**[AtomoPR]:**')) return true;
  if (text.startsWith('## Update:')) return true;
  if (text.includes('[Atomo Triage]')) return true;
  return false;
}

/**
 * Detect if a human has replied after the last bot comment that asked for input.
 * Skips status-only bot comments (e.g. "Clarification received") so they don't
 * reset the detection window and hide the user's actual reply.
 */
export function hasHumanReplyAfterBot(comments: Array<{ body: string; author: { login: string }; createdAt: string }>): boolean {
  if (!comments || comments.length === 0) return false;

  let lastBotIndex = -1;
  for (let i = comments.length - 1; i >= 0; i--) {
    const comment = comments[i];
    if (comment && isBotComment(comment.body) && !isBotStatusComment(comment.body)) {
      lastBotIndex = i;
      break;
    }
  }

  if (lastBotIndex === -1) {
    return comments.some(c => !isBotComment(c.body));
  }

  for (let i = lastBotIndex + 1; i < comments.length; i++) {
    const comment = comments[i];
    if (comment && !isBotComment(comment.body)) {
      return true;
    }
  }

  return false;
}

/**
 * Check if a PR has inline review comments newer than the last bot PR comment.
 * Inline review comments are NOT in gh --json comments — only available via REST API.
 */
export function hasNewReviewComments(prNumber: number, prComments: Array<{ body: string; createdAt: string }>, cwd?: string): boolean {
  try {
    // Find the timestamp of the last bot PR comment (our "addressed" marker)
    let lastBotTimestamp: string | null = null;
    for (let i = prComments.length - 1; i >= 0; i--) {
      const comment = prComments[i];
      if (comment && isBotComment(comment.body)) {
        lastBotTimestamp = comment.createdAt;
        break;
      }
    }

    // Fetch inline review comments via REST API
    const result = execSync(
      `gh api repos/{owner}/{repo}/pulls/${prNumber}/comments --jq '[.[] | .created_at]'`,
      { encoding: 'utf-8', cwd, stdio: ['pipe', 'pipe', 'pipe'] }
    );
    const timestamps: string[] = JSON.parse(result.trim());

    if (timestamps.length === 0) return false;

    // If no bot comment exists yet, any review comment counts as new
    if (!lastBotTimestamp) return true;

    // Check if any review comment is newer than the last bot response
    return timestamps.some(t => t > lastBotTimestamp);
  } catch {
    return false;
  }
}

/**
 * Extract issue number from a branch name like "atomo/issue-42"
 * or from a PR body containing "Resolves #42".
 */
export function extractIssueNumber(branchName: string, body: string): number | null {
  const branchMatch = branchName.match(/^atomo\/issue-(\d+)$/);
  if (branchMatch) return parseInt(branchMatch[1]!, 10);

  const bodyMatch = body?.match(/Resolves\s+#(\d+)/i);
  if (bodyMatch) return parseInt(bodyMatch[1]!, 10);

  return null;
}

// ─────────────────────────────────────────────────────────────────
// Git State Management Utilities (Issue #7)
// ─────────────────────────────────────────────────────────────────

/**
 * Represents the git state before agent work begins.
 */
export interface GitState {
  originalBranch: string;
  hadUncommittedChanges: boolean;
  stashCreated: boolean;
}

/**
 * Ensure the repository is on the latest main branch (or specified base branch).
 * Records the original state for later restoration.
 */
export function ensureLatestMain(cwd?: string, baseBranch: string = 'main'): {
  success: boolean;
  message: string;
  state?: GitState
} {
  const targetCwd = cwd || process.env.TARGET_REPO_PATH || process.cwd();

  try {
    // 1. Get current branch
    const originalBranch = execSync('git rev-parse --abbrev-ref HEAD', {
      encoding: 'utf-8',
      cwd: targetCwd
    }).trim();

    // 2. Check for uncommitted changes
    const statusOutput = execSync('git status --porcelain', {
      encoding: 'utf-8',
      cwd: targetCwd
    }).trim();

    const hadUncommittedChanges = statusOutput.length > 0;
    let stashCreated = false;

    // 3. If not on target base branch and has uncommitted changes, stash them
    if (originalBranch !== baseBranch && hadUncommittedChanges) {
      console.log(`[Git Validation] Stashing uncommitted changes on ${originalBranch}...`);
      execSync('git stash push -m "Atomo agent: auto-stash before validation"', {
        cwd: targetCwd,
        stdio: 'inherit'
      });
      stashCreated = true;
    }

    // 4. If not on base branch, checkout to it
    if (originalBranch !== baseBranch) {
      console.log(`[Git Validation] Checking out ${baseBranch} branch...`);
      execSync(`git checkout ${baseBranch}`, {
        cwd: targetCwd,
        stdio: 'inherit'
      });
    }

    // 5. Fetch latest from origin
    console.log(`[Git Validation] Fetching latest from origin/${baseBranch}...`);
    execSync(`git fetch origin ${baseBranch}`, {
      cwd: targetCwd,
      stdio: 'inherit'
    });

    // 6. Check if local is behind remote
    const localCommit = execSync(`git rev-parse ${baseBranch}`, {
      encoding: 'utf-8',
      cwd: targetCwd
    }).trim();

    const remoteCommit = execSync(`git rev-parse origin/${baseBranch}`, {
      encoding: 'utf-8',
      cwd: targetCwd
    }).trim();

    if (localCommit !== remoteCommit) {
      console.log(`[Git Validation] Pulling latest changes from origin/${baseBranch}...`);
      execSync(`git pull origin ${baseBranch}`, {
        cwd: targetCwd,
        stdio: 'inherit'
      });
    } else {
      console.log(`[Git Validation] Already up-to-date with origin/${baseBranch}.`);
    }

    return {
      success: true,
      message: `Repository is now on the latest ${baseBranch} branch.`,
      state: {
        originalBranch,
        hadUncommittedChanges,
        stashCreated
      }
    };

  } catch (error: any) {
    return {
      success: false,
      message: `Git validation failed: ${error.message}`
    };
  }
}

/**
 * Create a new feature branch from the current branch.
 */
export function createFeatureBranch(branchName: string, cwd?: string): {
  success: boolean;
  message: string
} {
  const targetCwd = cwd || process.env.TARGET_REPO_PATH || process.cwd();

  try {
    console.log(`[Git] Creating feature branch: ${branchName}...`);
    execSync(`git checkout -b ${branchName}`, {
      cwd: targetCwd,
      stdio: 'inherit'
    });

    return {
      success: true,
      message: `Branch ${branchName} created successfully.`
    };
  } catch (error: any) {
    return {
      success: false,
      message: `Failed to create branch ${branchName}: ${error.message}`
    };
  }
}

/**
 * Commit and push files to the current branch.
 */
export function commitAndPush(
  message: string,
  files: string[],
  cwd?: string
): { success: boolean; message: string } {
  const targetCwd = cwd || process.env.TARGET_REPO_PATH || process.cwd();

  try {
    // Add files
    files.forEach(file => {
      console.log(`[Git] Adding file: ${file}...`);
      execSync(`git add ${file}`, {
        cwd: targetCwd,
        stdio: 'inherit'
      });
    });

    // Commit
    console.log(`[Git] Committing: ${message}...`);
    execSync(`git commit -m "${message}\n\nCo-Authored-By: Claude Sonnet 4.5 <noreply@anthropic.com>"`, {
      cwd: targetCwd,
      stdio: 'inherit'
    });

    // Push to origin
    const currentBranch = execSync('git rev-parse --abbrev-ref HEAD', {
      encoding: 'utf-8',
      cwd: targetCwd
    }).trim();

    console.log(`[Git] Pushing to origin/${currentBranch}...`);
    execSync(`git push -u origin ${currentBranch}`, {
      cwd: targetCwd,
      stdio: 'inherit'
    });

    return {
      success: true,
      message: `Committed and pushed to origin/${currentBranch}.`
    };
  } catch (error: any) {
    return {
      success: false,
      message: `Failed to commit/push: ${error.message}`
    };
  }
}

/**
 * Check if a remote branch exists.
 */
export function remoteBranchExists(branchName: string, cwd?: string): boolean {
  const targetCwd = cwd || process.env.TARGET_REPO_PATH || process.cwd();

  try {
    execSync(`git fetch origin ${branchName}`, {
      cwd: targetCwd,
      stdio: 'pipe' // silence output
    });

    const result = execSync(`git ls-remote --heads origin ${branchName}`, {
      encoding: 'utf-8',
      cwd: targetCwd
    }).trim();

    return result.length > 0;
  } catch {
    return false;
  }
}

/**
 * Restore the repository to its original state.
 */
export function restorePreviousState(state: GitState, cwd?: string): {
  success: boolean;
  message: string
} {
  const targetCwd = cwd || process.env.TARGET_REPO_PATH || process.cwd();

  try {
    // 1. Checkout back to original branch
    if (state.originalBranch) {
      console.log(`[Git Cleanup] Returning to original branch: ${state.originalBranch}...`);
      execSync(`git checkout ${state.originalBranch}`, {
        cwd: targetCwd,
        stdio: 'inherit'
      });
    }

    // 2. Restore stashed changes
    if (state.stashCreated) {
      console.log(`[Git Cleanup] Restoring stashed changes...`);
      try {
        execSync('git stash pop', {
          cwd: targetCwd,
          stdio: 'inherit'
        });
      } catch (error: any) {
        if (error.message.includes('CONFLICT')) {
          return {
            success: false,
            message: 'Stash restoration failed due to conflicts. Your stashed changes are preserved. Run `git stash list` to see them, then manually resolve conflicts with `git stash pop`.'
          };
        }
        throw error;
      }
    }

    console.log(`[Git Cleanup] ✅ Repository restored to original state.`);
    return {
      success: true,
      message: 'Repository restored successfully.'
    };

  } catch (error: any) {
    return {
      success: false,
      message: `Failed to restore git state: ${error.message}\nManual intervention may be required.`
    };
  }
}
